### ISSUE TITLE
The version of package isn't right

### ISSUE THREAD

**Issue by Oroduin** [TinaMenke/Deep-Reinforcement-Learning#7]
It seems that some versions and package names in your requirements.txt are wrong.
For example, what is pkg-resources==0.0.0 in line 33?
It seems no matplotlib==3.0.3 in line 25.

Could you please correct the errors in it and release the new one?

**Comment by HongYegg** [comment]
Have you solved this problem?

**Comment by Oroduin** [comment]
yes

> Have you solved this problem?

**Comment by Oroduin** [comment]
The problem has been fixed
